### ISSUE TITLE
Erreur mysql à la connexion d'un auditeur

### ISSUE THREAD

**Issue by tigre-bleu** [archoad/evalsmsi#3]
Pour tester à partir du docker, j'ai créé:

Un utilisateur auditeur
2 établissements
1 groupement d'établissements
J'ai attribué le groupement à l'auditeur ainsi que les 2 établissements

Lorsque je me connecte en tant qu'auditeur j'ai l'erreur suivante:

`Fatal error: Uncaught Error: Object of class mysqli_result could not be converted to string in /home/www/evalsmsi/functions.php:1917 Stack trace: #0 /home/www/evalsmsi/functions.php(1917): sprintf() #1 /home/www/evalsmsi/audit.php(29): purgeRapportsFiles() #2 {main} thrown in /home/www/evalsmsi/functions.php on line 1917`

**Comment by archoad** [comment]
Merci sklaxs pour ton retour. Pas mieux ;-)
